select * from EMP;
-- LA MEJOR PRAXIS ES UTILIZAR EL NOMBRE DE LOS CAMPOS.
-- CONTROL + ENTER, EJECUTA LA LINEA EN LA QUE ESTEMOS POSICIONADOS.
select APELLIDO, OFICIO, SALARIO from EMP;
--ORDENACION DE DATOS, SIEMPRE AL FINAL Y AFECTA AL SELECT.
--LA ORDENACION SIEMPRE ES ASCENDENTE (asc).
select * from EMP order by APELLIDO asc;
--ORDENACION DESCENDENTE (desc).
select * from EMP order by APELLIDO desc;
--ORDENAR POR MAS DE UN CAMPO.
select * from EMP order by DEPT_NO, OFICIO;


-- FILTRADO DE REGISTROS.
-- OPERADORES DE COMPARACION.
/*
= igual
>= mayor o igual
<= menor o igual
< mayor
> menor
<> distinto
*/
-- Oracle, por defecto, diferencia entre mayúsculas y minúsculas en sus textos (string/varchar)
-- TODO LO QUE NO SEA UN NUMERO SE EXCRIBE ENTRE COMILLAS SIMPLES '.....'
-- PARA FILTRAR SE UTILIZA LA PALABRA where Y SE ESCRIBE SOLAMANTE UNA VEZ EN TODA LA CONSULTA
-- DESPUES DEL FROM
-- MOSTRAR TODOS LOS EMPLEADOS DEL DEPARTAMENTO 10
select * from EMP where DEPT_NO=10;

-- MOSTRAR TODOS LOS EMPLEADOS CUYO OFICIO SEA DIRECTOR
select * from EMP where OFICIO='DIRECTOR';

-- MOSTRAR TODOS LOPS EMPLEADOS CUYO OFICIO SEA DIFERENTE A DIRECTOR
select * from EMP where OFICIO<>'DIRECTOR';
select * from EMP where OFICIO!='DIRECTOR';


-- OPERADORES RELACONALES.
-- NOS PERMITEN REALIZAR MAS DE UNA PREGUNTA DENTRO DE UNA CONSULTA.
/*
OR --> MUESTRA DLOS DATOS DE CADA FILTRO
AND --> TODOS LOS FILTROS DEBEN CUMPLIRSE
NOT --> NEGACION DE UNA CONDICION (EVITARLOS SIEMPRE QUE SE PUEDA)
*/
-- MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10 Y QUE TENGAN OFICIO DIRECTOR
select * from EMP where DEPT_NO=10 and OFICIO='DIRECTOR';
select * from EMP where DEPT_NO=10 or OFICIO='DIRECTOR';

-- MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10 Y DEL DEPARTAMENTO 20
select * from EMP where DEPT_NO=10 or DEPT_NO=20;

-- TENEMOS OTROS OPERADORES ADEMAS DE LOS STANDARD
-- BETWEEN MUESTRA LOS DATOS ENTRE UN RANDO INCLUSIVE

-- MOSTRAR LOS EMPLEADOS CUYO SALARIO ESTE ENTRE 251000 Y 390000
select * from EMP where SALARIO between 251000 and 390000 order by SALARIO;

-- PODEMOS HACER LA MISMA CONSULTA CON OPERADORES Y ES EFICIENTE
select * from EMP where SALARIO >= 251000 and SALARIO <= 390000 order by SALARIO;

-- MOSTRAR LOS EMPLEADOS QUE NO SEAN DIRECTOR
select * from EMP where not OFICIO='DIRECTOR'; 

-- LA NEGACION ES ALGO DE LO QUE DEBEMOS HUIR
-- ES MEJOR REALIZAR LA CONSULTA CON OPERADOR
select * from EMP where OFICIO<>'DIRECTOR';

-- EXISTE UN OPERADOR PARA BUSCAR COINCIDENCIAS EN TEXTOS
-- NOS PERMITE, MEDIANTE CARACTERES ESPECIALES HACER FILTROS EN TEXTOS
/*
% busca cualquier caracter y longitud
_ un caracter cualquier
? un caracter numérico
*/
-- MOSTRAR LOS EMPLEADOS CUYO APELLIDO COMIENZA EN s
select * from EMP where APELLIDO like 's%';

-- MOSTRAR LOS EMPLEADOS CUYO APELLIDO COMIENZA EN s Y FINALIZA CON a
select * from EMP where APELLIDO like 's%a';

-- MOSTRAR TODOS LOS EMPLEADOS CUYO APELLIDO SEA DE 4 LETRAS
select * from EMP where APELLIDO like '____';

-- EXISTE OTRO OPERADOR PARA BUSCAR COINCIDENCIAS DE IGUALDAD EN UN MISMO CAMPO: in(valor1, valor2)
-- MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10 Y DEL DEPARTAMENTO 20, 30, 55, 65, 77
select * from EMP where DEPT_NO in (10, 20, 30, 55, 65, 77);

-- TENEMOS EL OPERADOR not in QUE REALIZA LO MISMO QUE in PERO RECUPERA LOS QUE NO COINCIDAN
-- MOSTRAR LOS EMPLEADOS QUE NO ESTEN EN EL DEPARTAMENTO 10 NI EN EL 20
select * from EMP where DEPT_NO not in (10, 20);


-- CAMPOS CALCULADOS.
-- UN CAMPO CALCULADO ES UNA HERRAMIENTA EN UNA CONSULTA QUE SIRVE PARA GENERAR CAMPOS QUE NO EXISTAN EN LA TABLA Y LO PODEMOS CALCULAR (SIEMPRE DEBE TENER UN ALIAS as)
-- UN CAMPO CALCULADO SOLO ES PARA EL CURSOR.
-- MOSTRAR EL APELLIDO, EL SALARIO, COMISION Y EL SALARIO TOTAL (SALARIO + COMISION) DE TODOS LOS EMPLEADOS CUYO SALARIO MAS COMISION SEA MAYOR 344500
select APELLIDO, SALARIO, COMISION, (SALARIO + COMISION) as TOTAL from EMP where (SALARIO + COMISION) >= 344500;

-- ORDENA LA CONSULTA ANTERIOR POR TOTAL
select APELLIDO, SALARIO, COMISION, (SALARIO + COMISION) as TOTAL from EMP where (SALARIO + COMISION) >= 344500 order by TOTAL;

-- CLAUSULA distinct SE UTILIZA PARA EL SELECT Y LO QUE REALIZA ES ELIMINAR REPETIDOS DE LA CONSULTA

-- MOSTRAR EL OFICIO DE LOS EMPLEADOS
select OFICIO from EMP;

-- MOSTRAR LOS DIFERENTES OFICIOS DE LOS EMPLEADOS;
select distinct OFICIO from EMP;

-- MOSTRAR LOS DIFERENTES OFICIOS, APELLIDOS DE LOS EMPLEADOS;
select distinct OFICIO, APELLIDO from EMP; 


-- EJERCICIOS DE PRUEBA.
-- Mostrar todos los enfermos nacidos antes del 11/01/1970
select * from ENFERMO where FECHA_NAC <= '11/01/1970';

-- Igual que el anterior, para los nacidos antes del 1/1/1970 ordenados por numero de inscripcion
select * from ENFERMO where FECHA_NAC <= '11/01/1970' order by INSCRIPCION;

-- Listar todos los datos de la plantilla del hospital del turno de mañana
select * from PLANTILLA where TURNO='M';

-- Idem del turno de noche
select * from PLANTILLA where TURNO='N';

-- Listar los doctores que su salario anual supere 3.000.0000   
select * from DOCTOR where (SALARIO * 12) > 3000000; 

-- Visualizar los empleados de la plantilla del turno de mañana que tengan un salario entre 200000 y 225000
select * from PLANTILLA where TURNO='M' and SALARIO >=200000 and SALARIO <=225000;
select * from PLANTILLA where TURNO='M'and SALARIO between 200000 and 225000;

-- Visualizar los empleados de la tabla EMP que no se dieron de alta entre el 01/01/1986 y el 12/12/1994
select * from EMP where FECHA_ALT <= '01/01/1986' or FECHA_ALT >= '12/12/1994';

-- Mostrar los nombres de los departamentos situados en Madrid o en Barcelona
select * from DEPT where LOC in ('MADRID', 'BARCELONA');


-- CONSULTA DE AGRUPACION.
-- ESTE TIPO DE CONSULTAS NOS PERMITE MOSTRAR ALGUN RESUMEN SOBRE UN GRUPO DETERMINADO DE LOS DATOS. UTILIZAN FUNCIONES DE AGRUPACIÓN PARA CONSEGUIR EL RESUMEN.
-- LAS FUNCIONES DEBEN TENER ALIAS.
/*
-- COUNT (*): Cuenta el numero de registros, incluyendo nulos
-- COUNT (CAMPO): Cuenta el número de registros sin nulos
-- SUM (NUMERO): Suma el total de un campo número
-- AVG (NUMERO): Recupera la media de un campo numérico
-- MAX (CAMPO): Devuelve el maximo valor de un campo
-- MIN (CAMPO): Devuelve el minimo valor de un campo
*/
-- MOSTRAR EL NUMERO DE REGISTTROS E LA TABAL DOCTOR.
select count(*) as NUMERO_DOCTORES from DOCTOR;
select count (APELLIDO) as NUMERO_DOCTORES from DOCTOR;

-- PODEMOS COMBINAR SIN PROBLEMA VARIAS FUNCIONES
-- MOSTRAR EL NUMERO DE DOCTORES Y EL MAXIMO SALARIO
select count(*) as DOCTORES, max(SALARIO) as MAXIMO from DOCTOR;

-- LOS DATOS RESULTANTES DE LAS FUNCIONES PODEMOS AGRUPARLOS POR ALGUN CAMPO/S DE LA TABLA.
-- CUANDO QUEREMOS AGRUPAR UTILIZAMOS group by DESPUES DEL from. DEBEMOS AGRUPAR POR CADA CAMPO QUE NO SEA UNA FUNCION.
-- MOSTRAR CUANTOS DOCTORES EXISTEN POR CADA ESPECIALIDAD
select count(*) as DOCTORES, ESPECIALIDAD
from DOCTOR
group by ESPECIALIDAD;

-- MOSTRAR NUMERO DE PERSONAS Y MAXIMO SALARIO DE LOS EMPLEADOS POR CADA DEPARTAMENTAO Y OFICIO.
select count(*) as PERSONAS, max(SALARIO) as MAXIMO_SALARIO, DEPT_NO, OFICIO
from EMP
group by DEPT_NO, OFICIO;

-- MOSTRAR EL NUMERO DE PERSONAS DE LA PLANTILLA
select count(*) as PERSONAS from PLANTILLA;

-- CUANTAS PERSONAS POR CADA TURNO DE LA PLANTILLA
select count(*) as PERSONAS, TURNO
from PLANTILLA
group by TURNO;

-- FILTRANDO EN CONSULTAS DE AGRUPACION.
-- TENEMOS DOS POSIBILIDADES:
-- WHERE: ANTES DEL group by
-- HAVING: DESPUES DEL group by
-- MOSTRAR CUANTOS EMPLEADOS TENEMOS POR CADA OFICIO QUE COBREN MAS DE 200000
select count(*) as EMPLEADOS, OFICIO
from EMP
where SALARIO > 200000
group by OFICIO;

-- HAVING: DESPUES DEL group by Y PARA FILTRAR SOBRE EL CONJUNTO
-- MOSTRAR CUANTOS EMPLEADOS TENEMOS POR CADA OFICIO Y QUE SEAN ANALISTAS O VENDEDOR
select count(*) as EMPLEADOS, OFICIO
from EMP
group by OFICIO
having OFICIO in ('ANALISTA', 'VENDEDOR');

select count(*) as EMPLEADOS, OFICIO
from EMP
where OFICIO in ('ANALISTA', 'VENDEDOR')
group by OFICIO;

-- CUANDO NO PODEMOS DECIDIR Y ESTAMOS OBLIGADOS A UTILIZAR having:
-- SI QUEREMOS FILTRAR POR UNA FUNCION DE AGRUPACION
-- MOSTRAR CUANTOS EMPLEADOS TENEMOS POR CADA OFICIO SOLAMENTE DONDE TENGAMOS 2 O MAS EMPLEADOS DL MISMO OFICIO
select count(*) as EMPLEADOS, OFICIO
from EMP
group by OFICIO
having count (*) >= 2;