-- CONSULTAS DE AGRUPACION (EJERCICIOS)
-- ENCONTRAR EL SALARIO MAS ALTO, MAS BAJO Y LA DIFERENCIA ENTRE AMBOS DE TODOS LOS EMPLEADOS CON OFICIO EMPLEADO
select * from EMP; --PARA VER LA TABLA
select OFICIO, max(SALARIO) as SALARIOMAXIMO, min(SALARIO) as SALARIOMINIMO, max(SALARIO) - min(SALARIO) as DIFERENCIA
from EMP
group by OFICIO
having OFICIO='EMPLEADO';

-- VISUALIZAR EL NUMERO DE PERSONAS QUE REALIZAN CADA OFICIO EN CADA DEPARTAMAENTO ORDENADO POR DEPARTAMENTO
select * from EMP; --PARA VER LA TABLA
select count (*) as PERSONAS, DEPT_NO, OFICIO
from EMP
group by DEPT_NO, OFICIO
order by DEPT_NO;

-- BUSCAR AQUELLOS DEPARTAMENTOS CON CUATRO O MAS PERSONAS TRABAJANDO
select * from EMP; --PARA VER LA TABLA
select count(*) as PERSONAS, DEPT_NO
from EMP
group by DEPT_NO
having count(*) >=4;

-- VISUALIZAR EL NUMERO DE ENFERMEROS, ENFERMERAS E INTERINOS QUE HAY EN UNA PLANTILLA, ORDENADOS POR LA FUNCION 
select * from PLANTILLA; --PARA VER LA TABLA
select count(*) as TRABAJADORES, FUNCION 
from PLANTILLA
group by FUNCION
having FUNCION in ('ENFERMERO', 'ENFERMERA', 'INTERINO');

-- VISUALIZAR DEPARTAMENTOS, OFICIOS Y NUMERO DE PERSONAS, PARA AQUELLOS DEPARTAMENTOS QUE TENGAN DOS O MAS PERSONAS TRABAJANDO EN EL MISMO OFICIO
select * from EMP; --PARA VER LA TABLA
select count(*) as PERSONAS, DEPT_NO, OFICIO
from EMP
group by DEPT_NO, OFICIO
having count(*) >=2;

-- CALCULAR EL VALOR MEDIDO DE LAS CAMAS QUE EXISTEN PARA CADA NOMBRE DE SALA. INDICAR EL NOMBRE DE CADA SALA Y EL NUMERO DE CADA UNA DE ELLAS
select * from SALA; --PARA VER LA TABLA
select count(*) as NUMERO, avg(NUM_CAMA) as MEDIA_CAMA, NOMBRE
from SALA 
group by NOMBRE;

-- CALCULAR EL SALARIO MEDIO DE LA PLANTILLA DE LA SALA 6, SEGUN LA FUNCION QUE REALIZAN. INDICAR LA FUNCION Y EL NUMERO DE EMPLEADOS
select FUNCION, count(*) as PERSONAS, avg(SALARIO) as MEDIA, SALA_COD
from PLANTILLA
group by FUNCION, SALA_COD
having sala_cod =6;

-- AVERIGUAR LOS ULTIMOS EMPLEADOS QUE SE DIERON DE ALTA EN LA EMPRESA EN CADA UNO DE LOS OFICIOS, ORDENADOS POR LA FECHA
select max(FECHA_ALT) as FECHAMAXIMA, OFICIO
from EMP
group by OFICIO
order by FECHAMAXIMA;

-- MOSTRAR EL NUMERO DE HOMBRES Y EL NUMERO DE MUJERES QUE HAY ENTRE LOS ENFERMOS
select * from ENFERMO; --PARA VER LA TABLA
select count (*) as ENFERMOS, SEXO
from ENFERMO
group by SEXO;

-- CALCULAR EL NUMERO DE SALAS QUE EXISTEN EN CADA HOSPITAL
select * from SALA; --PARA VER LA TABLA
select count(*) as NUMERO_SALAS, HOSPITAL_COD
from SALA
group by HOSPITAL_COD;

-- MOSTRAR EL NUMERO DE ENFERMERAS QUE EXISTAN POR CADA SALA
select count (*) as ENFERMERAS, SALA_COD
from PLANTILLA
group by SALA_COD;


-- CONSULTAS DE COMBINACION
-- NOS PERMITE MOSTRAT DATOS DE VARIAS TABLAS QUE DEBEN ESTAR RELACIONADAS ENTRE SI MEDIANTE ALGUNA CLAVE.
-- 1) NECESITAMOS LA COLUMNA O COLUMNAS (CAMPO/S) DE RELACION ENTRE LAS TABLAS
-- 2) DEBEMOS PONER EL NOMBRE DE CADA TABLA Y CADA COLUMNA (CAMPO) EN LA CONSULTA
-- SINTAXIS:
select TABLA1.CAMPO1, TABLA1.CAMPO2, TABLA2.CAMPO1, TABLA2.CAMPO2
from TABLA1
inner join TABLA2
on TABLA1.CAMPO_RELACION = TABLA2.CAMPO_RELACION;

--MOSTRAR EL APELLIDO, EL OFICIO DE EMPLEADOS JUNTO A SU NOMBRE DE DEPARTAMENTO Y LOCALIDAD
select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC
from EMP
inner join DEPT
on EMP.DEPT_NO = DEPT.DEPT_NO;

-- EN ORACLE TENENMOS OTRA SINTAXIS PARA REALIZAR LOS JOIN
select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC
from EMP, DEPT
where EMP.DEPT_NO = DEPT.DEPT_NO;
-- QUEREMOS MOSTRAR LOS DATOS SOLO DE MADRID
select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC
from EMP
inner join DEPT
on EMP.DEPT_NO = DEPT.DEPT_NO
where DEPT.LOC='MADRID';
-- PODEMOS INCLUIR ALIAS A LOS NOMBRES DE LAS TABLAS PARA LLAMARLAS ASI, A LO LARGO DE LA CONSULTA.
-- ES UTIL CUANDO TENEMOS TABLAS CON NOMBRE MUY LARGOS. CUANDO PONEMOS  ALIAS, LA TABLA SE LLAMARA ASI PARA TODA LA CONSULTA.
select e.APELLIDO, e.OFICIO, d.DNOMBRE, d.LOC
from EMP e
inner join DEPT d
on e.DEPT_NO = d.DEPT_NO
order by d.loc;

-- TENEMOS MULTIPLES TIPOS DE JOIN EN LAS BASES DE DATOS
-- inner: COMBINA LOS RESULTADOS DE LAS DOS TABLAS
-- left: COMBINA LAS DOS TABLAS Y TAMBIEN LA TABLA IZQUIERDA
-- right: COMBINA LAS DOS TABLAS Y FUERZA LA TABLA DERECHA
-- full: COMBINA LAS DOS (o mas tablas) Y FUERZA LAS DOS TABLAS
-- croos: PRODUCTO CARTESIANO, COMBINAR CADA DATO DE UNA TABLA CON LOS OTROS DATOS DE LA TABLA
select distinct dept_no 
from emp;
select * from dept;

-- TENEMOS UN DEPARTAMENTO: 40, PRODUCCION, GRANADA SIN EMPLEADOS
-- VAMOS A CREAR UN NUEVO EMPLEADO QUE NO TENGA DEPARTAMENTO
-- TENEMOS UN EMPLEADO SIN DEPARTAMENTO EN EL 50 (LO HEMOS AÑADIDO INSERT INTO emp VALUES('7839', 'rey', 'PRESIDENTE', NULL, TO_DATE('17-11-1995', 'DD-MM-YYYY'), 650000, NULL, 10);)
select emp.apellido, dept.dnombre, dept.loc
from emp
inner join dept
on emp.dept_no = dept.dept_no;
-- left: COMBINA LAS DOS TABLAS Y TAMBIEN LA TABLA IZQUIERDA
-- LA TABLA DE LA IZQUIERDA ES ANTES DEL JOIN
select emp.apellido, dept.dnombre, dept.loc
from emp
left join dept
on emp.dept_no = dept.dept_no;
-- right: COMBINA LAS DOS TABLAS Y TAMBIEN LA TABLA DERECHA
-- LA TABLA DE LA DERECHA ES DESPUES DEL JOIN
select emp.apellido, dept.dnombre, dept.loc
from emp
right join dept
on emp.dept_no = dept.dept_no;
-- full: COMBINA LAS DOS TABLAS Y TAMBIEN LOS DATOS QUE NO COMBIEN
select emp.apellido, dept.dnombre, dept.loc
from emp
full join dept
on emp.dept_no = dept.dept_no;
--cross: PRODUCTO CARTESIANO. NO LLEVA ON
select emp.apellido, dept.dnombre, dept.loc
from emp
cross join dept;


-- MOSTRA LA MEDIA SALARIAL DE LOS DOCTORES POR HOSPITAL
select * from DOCTOR;--PARA VER LA TABLA
select * from HOSPITAL;--PARA VER LA TABLA
select avg(SALARIO) as MEDIA, HOSPITAL_COD
from DOCTOR
group by HOSPITAL_COD;

-- MOSTRA LA MEDIA SALARIAL DE LOS DOCTORES POR HOSPITAL, MOSTRANDO EL NOMBRE DEL HOSPITAL
select * from DOCTOR;--PARA VER LA TABLA
select * from HOSPITAL;--PARA VER LA TABLA
select avg(DOCTOR.SALARIO) as MEDIA, HOSPITAL.NOMBRE
from DOCTOR
inner join HOSPITAL
on DOCTOR.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD
group by HOSPITAL.NOMBRE;

-- MOSTRAR EL NUMERO DE EMPLEADOS QUE EXISTEN POR CADA LOCALIDAD
select * from emp;
select * from dept;
select count(EMP.EMP_NO) as NUMERO_EMP, DEPT.LOC
from EMP
right join DEPT
on EMP.DEPT_NO = DEPT.DEPT_NO
group by DEPT.LOC;